/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.86
 * Generated at: 2024-04-30 05:05:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/header.jsp", Long.valueOf(1714453538741L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.js\"></script>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/base.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<div ><label class=\"index\">cloud</label></div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<c:choose>\r\n");
      out.write("	<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sss }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		<div><button class=\"btn join\">회원가입</button></div>\r\n");
      out.write("		<div><button class=\"btn login\">로그인</button></div>\r\n");
      out.write("	</c:when>\r\n");
      out.write("	<c:otherwise>\r\n");
      out.write("		<div>[[ 아이디 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sss.gamerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ]]</div>\r\n");
      out.write("		\r\n");
      out.write("		<form id=\"frm-logout\">\r\n");
      out.write("		<div><button class=\"btn logout\">로그아웃</button></div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</c:otherwise>\r\n");
      out.write("</c:choose>\r\n");
      out.write("<div><button class=\"btn shop\">상점</button></div>\r\n");
      out.write("<div><button class=\"btn board\">게시판</button></div>\r\n");
      out.write("\r\n");
      out.write("<!-- 아래는 스크립트만 -->\r\n");
      out.write("<script>\r\n");
      out.write("$(loadedHandler);\r\n");
      out.write("function loadedHandler(){\r\n");
      out.write("	//event 등록\r\n");
      out.write("	$(\".index\").on(\"click\", indexClickHandler);\r\n");
      out.write("	$(\".btn.join\").on(\"click\", btnJoinClickHandler);\r\n");
      out.write("	$(\".btn.login\").on(\"click\", btnLoginClickHandler);\r\n");
      out.write("	$(\".btn.shop\").on(\"click\", btnShopClickHandler);\r\n");
      out.write("	$(\".btn.board\").on(\"click\", btnBoardClickHandler);\r\n");
      out.write("	$(\".btn.logout\").on(\"click\", btnLogoutClickHandler);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function indexClickHandler(){\r\n");
      out.write("	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\";\r\n");
      out.write("}\r\n");
      out.write("function btnJoinClickHandler(){\r\n");
      out.write("	//window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join\",\"_blank\", \"toolbar=yes,scrollbars=yes,resizable=yes,top=500,left=500,width=400,height=400\");\r\n");
      out.write("	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/join\";\r\n");
      out.write("}\r\n");
      out.write("function btnLoginClickHandler(){\r\n");
      out.write("	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\";\r\n");
      out.write("}\r\n");
      out.write("function btnShopClickHandler(){\r\n");
      out.write("	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/shop/list\";\r\n");
      out.write("}\r\n");
      out.write("function btnBoardClickHandler(){\r\n");
      out.write("	location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/community/list\";	\r\n");
      out.write("}\r\n");
      out.write("function btnLogoutClickHandler(){\r\n");
      out.write("	// get방식으로 사용하지 않음\r\n");
      out.write("	// location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\";\r\n");
      out.write("	//\r\n");
      out.write("	\r\n");
      out.write("	alert(\"로그아웃되었습니다.\");\r\n");
      out.write("	\r\n");
      out.write("	var frmlogout = document.getElementById(\"frm-logout\");\r\n");
      out.write("	frmlogout.action = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\";\r\n");
      out.write("	frmlogout.method = \"post\";\r\n");
      out.write("	frmlogout.submit();\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>login</h1>\r\n");
      out.write("<fieldset>\r\n");
      out.write("	<legend>login</legend>\r\n");
      out.write("	<form id=\"cloud-login\">\r\n");
      out.write("		<div><label>아이디</label><input type=\"text\" name=\"id\"></div>\r\n");
      out.write("		<div><label>비밀번호</label><input type=\"password\" name=\"pwd\"></div>\r\n");
      out.write("		<div><input type=\"button\" value=\"로그인\" class=\"btn submit\"></div>\r\n");
      out.write("		<div><p class=\"erm\">asd</p></div>\r\n");
      out.write("	</form>\r\n");
      out.write("</fieldset>\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(loadedHandler);\r\n");
      out.write("function loadedHandler(){\r\n");
      out.write("	$(\"#cloud-login .btn.submit\").on(\"click\",loginClickHandler);\r\n");
      out.write("}\r\n");
      out.write("function loginClickHandler(){\r\n");
      out.write("	console.log($(\"#cloud-login\").serialize());\r\n");
      out.write("	console.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\")\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\"\r\n");
      out.write("		,method : \"post\"\r\n");
      out.write("		,data : $(\"#cloud-login\").serialize()\r\n");
      out.write("		,success : function(result){\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			if(result == 1 ){\r\n");
      out.write("				//alert(\"반갑습니다.\");\r\n");
      out.write("				var prePage = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prePage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("				if(prePage == \"write\"){\r\n");
      out.write("					location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/commu/list\";\r\n");
      out.write("				}\r\n");
      out.write("				location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index\";\r\n");
      out.write("			}else {\r\n");
      out.write("				$(\".erm\").html(\"비밀번호와 계정 이름이 맞는지 확인하고 다시 시도하세요.\");\r\n");
      out.write("				$(\"[name=pwd]\").val(\"\");\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		,error : function(request, status, error){\r\n");
      out.write("			alert(\"code: \"+request.status + \"\\n\" + \"message: \" \r\n");
      out.write("					+ request.responseText + \"\\n\"\r\n");
      out.write("					+ \"error: \"+error);\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
